[package]
name = "gauche"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "5.5.1"
toml = "0.8.23"
serde = { version = "1.0.219", features = ["derive"] }
strum = { version = "0.27.1", features = ["derive"] }
strum_macros = "0.27.1"
glam = "0.30.4"
